name: Generate Pull Request
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches-ignore:
      - master


jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Create pull request on commit using REST API
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/pulls \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "Automated Pull Request from: ${{ github.ref }}",
          "head" : "${{ github.ref }}",
          "base" : "master"
          }'
